server:
  port: ${SERVER_PORT:8000}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: user-service
            uri: ${USER_SERVICE_URL:http://localhost:8080}
            predicates:
            - Path=/api/users/**

          - id: board-service-jwt
            uri: ${BOARD_SERVICE_URL:http://localhost:8081}
            predicates:
            - Path=/api/boards
            - Method=POST
            filters:
            - JwtAuthenticationFilter

          - id: board-service
            uri: ${BOARD_SERVICE_URL:http://localhost:8081}
            predicates:
            - Path=/api/boards/**
